environment        = "prod"
kubeconfig_path    = "~/.kube/vyking-prod-config"
argocd_namespace   = "argocd"
apps_namespace     = "default"
repo_url           = "https://github.com/lauj0rge/vyking-devops-task.git"
repo_branch        = "prod"
frontend_namespace = "frontend-prod"
backend_namespace  = "backend-prod"
mysql_namespace    = "mysql-prod"

