replicaCount: 2

image:
  tag: prod

service:
  port: 8081

mysql:
  host: mysql-prod
  secretName: mysql-prod-secret

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70
  memoryUtilization: 70
