replicaCount: 2

image:
  repository: vyking-backend
  tag: prod
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

mysql:
  host: mysql-prod
  port: 3306
  secretName: mysql-prod-secret

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  liveness:
    path: /health
    initialDelaySeconds: 5
  readiness:
    path: /ready
    initialDelaySeconds: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
