replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: latest

service:
  port: 8081

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 60
