replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: latest
  pullPolicy: IfNotPresent

#service:
#  type: ClusterIP
#  port: 8080

service:
  type: ClusterIP
  port: 5678   # http-echo expone por defecto el 5678

args:
  - "-text=hello backend"
  -
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

#probes:
#  liveness:
#    path: /
#    initialDelaySeconds: 10
#    periodSeconds: 15
#    timeoutSeconds: 2
#    failureThreshold: 3
#  readiness:
#    path: /
#    initialDelaySeconds: 5
#    periodSeconds: 10
#    timeoutSeconds: 2
#    failureThreshold: 3
probes:
  liveness:
    path: /
    port: 5678
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    path: /
    port: 5678
    initialDelaySeconds: 5
    periodSeconds: 10

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70
  memoryUtilization: null # can set a percentage here

labels:
  app.kubernetes.io/name: backend
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: vyking-app
