replicaCount: 3

image:
  repository: hashicorp/http-echo
  tag: "0.2.3"

service:
  port: 8080

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  cpuUtilization: 70
  memoryUtilization: 80
