replicaCount: 1

image:
  repository: vyking-backend
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

mysql:
  host: mysql-dev
  port: 3306
  secretName: mysql-dev-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

probes:
  liveness:
    path: /health
    initialDelaySeconds: 5
  readiness:
    path: /ready
    initialDelaySeconds: 3

autoscaling:
  enabled: false
