replicaCount: 1

image:
  tag: dev

service:
  port: 8081

mysql:
  host: mysql-dev
  secretName: mysql-dev-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
