apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: frontend-{{ .Values.environment | default "dev" }}
data:
  default.conf: |
    server {
      listen 80;

      # Serve frontend app
      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri /index.html;
      }

      # Proxy API calls to backend
      location /api/ {
        proxy_pass http://backend-backend.backend-{{ .Values.environment | default "dev" }}.svc.cluster.local:{{ .Values.backend.port }}/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
    }
