apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    argocd.argoproj.io/external-url: "https://frontend-{{ .Values.environment }}.local:8443/"
spec:
  rules:
    - host: frontend-dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ .Values.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-backend
                port:
                  number: 8081
  tls:
    - secretName: frontend-tls-dev
      hosts:
        - frontend-dev.local
