mysql:
  architecture: standalone

  auth:
    existingSecret: mysql-prod-secret

  primary:
    persistence:
      size: 5Gi
    service:
      port: 3306

  initdbScripts:
    init.sql: |
      CREATE TABLE IF NOT EXISTS todos (
        id INT AUTO_INCREMENT PRIMARY KEY,
        task VARCHAR(255) NOT NULL
      );

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

commonLabels:
  environment: prod
  app: vyking-mysql
