mysql:
  architecture: standalone

  auth:
    rootPassword: changeme
    database: mydb
    username: user
    password: password

  primary:
    persistence:
      enabled: true
      size: 5Gi
    service:
      type: ClusterIP
      port: 3306

  # Security hardening
  podSecurityContext:
    enabled: true
    runAsUser: 1001
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL

  # Resource constraints
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi

  # Probes
  primary:
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 5

# Labels
commonLabels:
  app.kubernetes.io/name: mysql
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: vyking-app
