global:
  environment: prod

frontend:
  namespace: frontend-prod
  replicaCount: 2
  image:
    tag: prod
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: frontend-prod.example.com
        paths:
          - path: /
            pathType: Prefix
            service:
              component: frontend
          - path: /api
            pathType: Prefix
            service:
              component: backend
    tls:
      - secretName: frontend-tls-prod
        hosts:
          - frontend-prod.example.com
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 60
    memoryUtilization: 75
  backendService:
    host: backend-backend.backend-prod.svc.cluster.local
    port: 8081

backend:
  namespace: backend-prod
  replicaCount: 2
  image:
    tag: prod
  service:
    port: 8081
  mysql:
    host: mysql-prod
    secretName: mysql-credentials-prod
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  probes:
    liveness:
      path: /health
      port: 8081
      initialDelaySeconds: 5
    readiness:
      path: /health
      port: 8081
      initialDelaySeconds: 3
  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 70
    memoryUtilization: 70
  labels:
    environment: prod
