global:
  environment: prod

frontend:
  enabled: true
  namespace: frontend-prod
  image:
    tag: prod
  service:
    port: 8080
    targetPort: 8081
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: frontend.example.com
        paths:
          - path: /
            pathType: Prefix
            service:
              component: frontend
          - path: /api
            pathType: Prefix
            service:
              component: backend
              port: 8081
    tls:
      - secretName: frontend-tls-prod
        hosts:
          - frontend.example.com
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 70
    memoryUtilization: 80
  backendService:
    host: backend-backend.backend-prod.svc.cluster.local
    port: 8081

backend:
  enabled: true
  namespace: backend-prod
  image:
    tag: prod
  mysql:
    secretName: mysql-credentials-prod
  ingress:
    enabled: true
    host: frontend.example.com
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  probes:
    liveness:
      path: /health
      port: 8081
      initialDelaySeconds: 10
      periodSeconds: 15
      timeoutSeconds: 3
      failureThreshold: 3
    readiness:
      path: /health
      port: 8081
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 5
  labels:
    environment: prod
