global:
  environment: dev

frontend:
  enabled: true
  namespace: frontend-dev
  replicaCount: 1
  image:
    repository: vyking-frontend
    tag: dev
    pullPolicy: Never
  service:
    port: 8080
    targetPort: 80
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: frontend-dev.local
        paths:
          - path: /
            pathType: Prefix
          - path: /api
            pathType: Prefix
    tls:
      - secretName: frontend-tls-dev
        hosts:
          - frontend-dev.local
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilization: 70
    memoryUtilization: 80
backend:
  enabled: false