global:
  environment: dev

frontend:
  namespace: frontend-dev
  image:
    tag: dev
  service:
    port: 8080
    targetPort: 80
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: frontend-dev.local
        paths:
          - path: /
            pathType: Prefix
            service:
              component: frontend
          - path: /api
            pathType: Prefix
            service:
              component: backend
              port: 8081
    tls:
      - secretName: frontend-tls-dev
        hosts:
          - frontend-dev.local
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilization: 70
    memoryUtilization: 80
  backendService:
    host: backend-backend.backend-dev.svc.cluster.local
    port: 8081

backend:
  namespace: backend-dev
  image:
    tag: dev
  mysql:
    secretName: mysql-credentials-dev
  ingress:
    enabled: true
    host: frontend-dev.local
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 128Mi
  probes:
    liveness:
      path: /health
      port: 8081
      initialDelaySeconds: 10
      periodSeconds: 15
      timeoutSeconds: 3
      failureThreshold: 3
    readiness:
      path: /health
      port: 8081
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 5
  labels:
    environment: dev
