global:
  environment: dev

frontend:
  namespace: frontend-dev
  replicaCount: 1
  image:
    repository: vyking-frontend
    tag: dev
    pullPolicy: IfNotPresent
  service:
    port: 8080
    targetPort: 80
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: frontend-dev.local
        paths:
          - path: /
            pathType: Prefix
          - path: /api
            pathType: Prefix
    tls:
      - secretName: frontend-tls-dev
        hosts:
          - frontend-dev.local
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilization: 70
    memoryUtilization: 80

backend:
  namespace: backend-dev
  replicaCount: 1
  image:
    repository: vyking-backend
    tag: dev
    pullPolicy: IfNotPresent
  mysql:
    secretName: mysql-credentials-dev
  ingress:
    enabled: true
    host: frontend-dev.local
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 128Mi
  probes:
    liveness:
      path: /health
      port: 8081
      initialDelaySeconds: 10
      periodSeconds: 15
      timeoutSeconds: 3
      failureThreshold: 3
    readiness:
      path: /health
      port: 8081
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 5
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilization: 70
    memoryUtilization: 80

  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: vyking-app
    environment: dev


