global:
  environment: dev

frontend:
  enabled: false

backend:
  enabled: true
  namespace: backend-dev
  replicaCount: 1
  image:
    repository: vyking-backend
    tag: dev
    pullPolicy: never
  mysql:
    secretName: mysql-credentials-dev
  ingress:
    enabled: true
    host: frontend-dev.local
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  probes:
    liveness:
      path: /health
      port: 8081
      initialDelaySeconds: 10
      periodSeconds: 15
      timeoutSeconds: 3
      failureThreshold: 3
    readiness:
      path: /health
      port: 8081
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 5
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilization: 70
    memoryUtilization: 80

  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: vyking-app
    environment: dev
