global:
  environment: prod

frontend:
  namespace: frontend-prod
  replicaCount: 2
  image:
    tag: prod
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: frontend-prod.example.com
        paths:
          - path: /
            pathType: Prefix
          - path: /api
            pathType: Prefix
    tls:
      - secretName: frontend-tls-prod
        hosts:
          - frontend-prod.example.com
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  probes:
    liveness:
      path: /
      port: 80
      initialDelaySeconds: 5
      periodSeconds: 15
    readiness:
      path: /
      port: 80
      initialDelaySeconds: 3
      periodSeconds: 10
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 60
    memoryUtilization: 75

backend:
  namespace: backend-prod
  replicaCount: 2
  image:
    tag: prod
  service:
    port: 8081
  mysql:
    host: mysql-prod
    secretName: mysql-credentials-prod
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  probes:
    liveness:
      path: /health
      port: 8081
      initialDelaySeconds: 5
    readiness:
      path: /health
      port: 8081
      initialDelaySeconds: 3
  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 70
    memoryUtilization: 70
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: vyking-app
    environment: prod
