replicaCount: 2

image:
  tag: prod

backend:
  host: backend-backend.backend-prod.svc.cluster.local
  port: 8081

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 60
  memoryUtilization: 75

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: frontend-prod.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-tls-prod
      hosts:
        - frontend-prod.example.com
