replicaCount: 2

image:
  tag: prod

backend:
  host: backend-backend.backend-prod.svc.cluster.local
  port: 8081

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 60
  memoryUtilization: 75
