replicaCount: 1

image:
  tag: dev

backend:
  host: backend-backend.backend-dev.svc.cluster.local
  port: 8081

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70
  memoryUtilization: 80
