replicaCount: 1

image:
  tag: dev

backend:
  host: backend-backend.backend-dev.svc.cluster.local
  port: 8081

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70
  memoryUtilization: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: frontend-dev.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-tls-dev
      hosts:
        - frontend-dev.local
