apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: vyking-app
    app.kubernetes.io/environment: {{ .Values.commonLabels.environment | default "dev" }}
spec:
  schedule: "0 2 * * *" # every day at 2am
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: bitnami/mysql:8.0
              command:
                - /bin/sh
                - -c
                - |
                  mysqldump -h {{ .Release.Name }}-mysql -u{{ .Values.mysql.auth.username }} \
                    -p{{ .Values.mysql.auth.password }} {{ .Values.mysql.auth.database }} > /backups/db-$(date +%F).sql
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: mysql-backups
