apiVersion: v2
name: mysql
description: A Helm chart for deploying MySQL with environment-specific values
type: application
version: 0.1.0
dependencies:
  - name: mysql
    version: 14.0.3
    repository: https://charts.bitnami.com/bitnami
