{{- if .Values.frontend.enabled }}
{{- $root := . -}}
{{- $frontend := $root.Values.frontend -}}
{{- $name := include "vyking-app.frontendFullname" $root -}}
{{- $namespace := default $root.Release.Namespace $frontend.namespace -}}
{{- $backendNamespace := default $root.Release.Namespace $root.Values.backend.namespace -}}
{{- $backendService := include "vyking-app.backendFullname" $root -}}
{{- $backendHost := default (printf "%s.%s.svc.cluster.local" $backendService $backendNamespace) $frontend.backend.host -}}
{{- $backendPort := default $root.Values.backend.service.port $frontend.backend.port -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-nginx-config" $name }}
  namespace: {{ $namespace }}
data:
  default.conf: |
    server {
      listen 80;

      # Serve frontend app
      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri /index.html;
      }

      # Proxy API calls to backend
      location /api/ {
        proxy_pass http://{{ $backendHost }}:{{ $backendPort }}/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
    }
{{- end }}
