{{- if and .Values.frontend.enabled .Values.frontend.hpa.enabled }}
{{- $root := . -}}
{{- $frontend := $root.Values.frontend -}}
{{- $name := include "vyking-app.frontendFullname" $root -}}
{{- $namespace := default $root.Release.Namespace $frontend.namespace -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: vyking-app
    environment: {{ include "vyking-app.environment" $root }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ $frontend.hpa.minReplicas }}
  maxReplicas: {{ $frontend.hpa.maxReplicas }}
  metrics:
  {{- if $frontend.hpa.cpuUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $frontend.hpa.cpuUtilization }}
  {{- end }}
  {{- if $frontend.hpa.memoryUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $frontend.hpa.memoryUtilization }}
  {{- end }}
{{- end }}
