{{- if and .Values.frontend.enabled .Values.frontend.ingress.enabled }}
{{- $root := . -}}
{{- $frontend := $root.Values.frontend -}}
{{- $name := include "vyking-app.frontendFullname" $root -}}
{{- $namespace := default $root.Release.Namespace $frontend.namespace -}}
{{- $annotations := dict -}}
{{- $_ := set $annotations "argocd.argoproj.io/external-url" (printf "https://frontend-%s.local:8443/" (include "vyking-app.environment" $root)) -}}
{{- range $key, $value := $frontend.ingress.annotations }}
{{- $_ := set $annotations $key $value -}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  annotations:
    {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
{{ if $frontend.ingress.hosts }}
  rules:
    {{- range $frontend.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- if .paths }}
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $frontend.service.port }}
          {{- end }}
          {{- else }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $frontend.service.port }}
          {{- end }}
    {{- end }}
{{ end }}
{{- if $frontend.ingress.tls }}
  tls:
{{- toYaml $frontend.ingress.tls | nindent 4 }}
{{- end }}
{{- end }}
