apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: {{ .Values.backup.image }}
              command:
                - sh
                - -c
                - >
                  mysqldump -h mysql
                  -u{{ .Values.mysql.username }}
                  -p"$MYSQL_PASSWORD"
                  {{ .Values.mysql.database }}
                  > /backup/db-$(date +\%F-\%H-\%M).sql
              envFrom:
                - secretRef:
                    name: {{ .Values.mysql.secretName }}
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: {{ .Values.backup.pvc }}
