apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: mysql:8.0
              command:
                - /bin/sh
                - -c
                - |
                  mysqldump \
                    -h mysql.mysql-dev.svc.cluster.local \
                    -P 3306 \
                    -u $MYSQL_USER \
                    -p$MYSQL_PASSWORD \
                    $MYSQL_DATABASE > /backup/backup.sql
              envFrom:
                - secretRef:
                    name: mysql-credentials-dev

              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: {{ .Values.backup.pvc }}

