apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: bitnami/mysql:8.0
              command:
                - sh
                - -c
                - >
                  mysqldump -h mysql.${ENVIRONMENT}.svc.cluster.local
                  -uroot
                  -p${MYSQL_ROOT_PASSWORD}
                  ${MYSQL_DATABASE}
                  > /backup/db-$(date +\%F-\%H-\%M).sql

              env:
                - name: ENVIRONMENT
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.auth.existingSecret }}
                      key: rootPassword
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.auth.existingSecret }}
                      key: database
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-backups