apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: mysql-dev
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: {{ .Values.backup.image }}
              command:
                - sh
                - -c
                - >
                  mysqldump
                  -h {{ .Values.mysql.host }}
                  -u{{ .Values.mysql.username }}
                  -p"$MYSQL_PASSWORD"
                  {{ .Values.mysql.database }}
                  > /backup/db-$(date +%%F-%%H-%%M).sql
              env:
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.mysql.secretName }}
                      key: password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: {{ .Values.backup.pvc }}
