apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: {{ .Release.Namespace }}
data:
  cleanup.sh: |
    #!/bin/bash
    echo "Checking for previous failed startup..."
    if [ -f /opt/bitnami/mysql/data/mysql.sock ]; then
        echo "Removing stale socket file..."
        rm -f /opt/bitnami/mysql/data/mysql.sock
    fi
    if [ -f /opt/bitnami/mysql/tmp/mysql.sock ]; then
        echo "Removing stale tmp socket file..."
        rm -f /opt/bitnami/mysql/tmp/mysql.sock
    fi
    echo "Cleanup completed."