apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: {{ .Release.Namespace }}
data:
  mysql-init.sql: |
    CREATE DATABASE IF NOT EXISTS devdb;
    CREATE USER IF NOT EXISTS 'devuser'@'%' IDENTIFIED BY 'devpass123';
    GRANT ALL PRIVILEGES ON devdb.* TO 'devuser'@'%';
    FLUSH PRIVILEGES;
