---
image:
  repository: bitnami/mysql
  tag: 8.0
  pullPolicy: IfNotPresent

auth:
  existingSecret: mysql-dev-secret
  username: devuser
  database: devdb
  secretKeys:
    rootPasswordKey: rootPassword
    usernameKey: username
    passwordKey: password
    databaseKey: database

primary:
  persistence:
    enabled: true
    size: 1Gi

initdbScripts:
  leaderboard.sql: |
    DROP TABLE IF EXISTS player_leaderboard;
    CREATE TABLE player_leaderboard (
      player_id INT AUTO_INCREMENT PRIMARY KEY,
      gamer_tag VARCHAR(50) NOT NULL,
      region VARCHAR(20) NOT NULL,
      player_level INT NOT NULL,
      total_matches INT NOT NULL,
      win_rate DECIMAL(5,2) NOT NULL,
      avg_session_length DECIMAL(4,1) NOT NULL,
      favorite_mode VARCHAR(40) NOT NULL,
      last_login DATETIME NOT NULL
    );
