auth:
  existingSecret: mysql-dev-secret
  secretKeys:
    rootPassword: mysql-root-password
    username: mysql-username
    password: mysql-password
    database: mysql-database

backup:
  schedule: "0 */48 * * *"   # every 2 days
  pvc: mysql-backups
  envFromSecret:
    name: mysql-dev-secret

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

primary:
  persistence:
    size: 8Gi
  initContainers:
    - name: init-mysql
      image: mysql:8.0
      command: ['bash', '-c']
      args:
        - |
          # Wait for MySQL to be ready
          while ! mysql -h mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"; do
            sleep 5
          done
          # Run initialization scripts
          mysql -h mysql -uroot -p${MYSQL_ROOT_PASSWORD} < /scripts/init.sql
      volumeMounts:
        - name: init-scripts
          mountPath: /scripts
  extraVolumes:
    - name: init-scripts
      configMap:
        name: mysql-init