auth:
  existingSecret: mysql-dev-secret
  secretKeys:
    rootPassword: mysql-root-password
    username: mysql-username
    password: mysql-password
    database: mysql-database

backup:
  schedule: "0 */48 * * *"   # every 2 days
  pvc: mysql-backups
  envFromSecret:
    name: mysql-dev-secret

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

primary:
  initdbScriptsConfigMap: mysql-init
  persistence:
    size: 8Gi
  startupProbe:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  configuration: |-
    [mysqld]
    skip-grant-tables
    skip-networking
  extraInitContainers: |
    - name: reset-root-password
      image: docker.io/bitnami/mysql:8.0.36
      command:
        - /bin/bash
        - -c
        - |
          # Wait for MySQL to start with skip-grant-tables
          sleep 30
          # Connect without password and set root password
          mysql -uroot <<EOF
          FLUSH PRIVILEGES;
          ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
          FLUSH PRIVILEGES;
          EOF

