---
image:
  repository: bitnami/mysql
  tag: 8.0
  pullPolicy: IfNotPresent

auth:
  existingSecret: mysql-dev-secret
  username: devuser
  database: devdb
  secretKeys:
    rootPasswordKey: rootPassword
    usernameKey: username
    passwordKey: userPassword
    databaseKey: database

primary:
  persistence:
    enabled: true
    size: 1Gi

initdbScripts:
  leaderboard.sql: |
    DROP TABLE IF EXISTS player_leaderboard;
    CREATE TABLE player_leaderboard (
      player_id INT AUTO_INCREMENT PRIMARY KEY,
      gamer_tag VARCHAR(50) NOT NULL,
      region VARCHAR(20) NOT NULL,
      player_level INT NOT NULL,
      total_matches INT NOT NULL,
      win_rate DECIMAL(5,2) NOT NULL,
      avg_session_length DECIMAL(4,1) NOT NULL,
      favorite_mode VARCHAR(40) NOT NULL,
      last_login DATETIME NOT NULL
    );

    INSERT INTO player_leaderboard
      (gamer_tag, region, player_level, total_matches, win_rate, avg_session_length, favorite_mode, last_login)
    VALUES
      ('ShadowNinja', 'EU', 45, 320, 58.75, 42.5, 'Battle Royale', '2025-09-20 10:15:00'),
      ('DragonSlayer', 'NA', 60, 540, 64.20, 38.2, 'Arena', '2025-09-19 23:47:00'),
      ('PixelMage', 'ASIA', 28, 150, 47.00, 29.7, 'Capture the Flag', '2025-09-18 14:02:00'),
      ('IronFist', 'EU', 35, 210, 52.10, 33.1, 'Deathmatch', '2025-09-20 01:20:00'),
      ('CyberWolf', 'SA', 50, 400, 61.35, 40.8, 'Survival', '2025-09-17 19:10:00');

  grants.sql: |
    CREATE USER IF NOT EXISTS 'devuser'@'%' IDENTIFIED WITH caching_sha2_password BY 'devpass123';
    GRANT ALL PRIVILEGES ON devdb.* TO 'devuser'@'%';
    FLUSH PRIVILEGES;

