auth:
  existingSecret: mysql-dev-secret

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

backup:
  schedule: "0 */6 * * *"   # every 6 hours
  image: mysql:8.0
  pvc: mysql-backups

primary:
  persistence:
    size: 8Gi
