auth:
  existingSecret: mysql-prod-secret
  secretKeys:
    rootPassword: mysql-root-password
    username: mysql-username
    password: mysql-password
    database: mysql-database

backup:
  schedule: "0 */48 * * *"   # every 2 days
  pvc: mysql-backups
  envFromSecret:
    name: mysql-prod-secret

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

primary:
  initdbScriptsConfigMap: mysql-init
  persistence:
    size: 8Gi
