auth:
  existingSecret: mysql-dev-secret

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

backup:
  schedule: "0 */6 * * *"   # every 6 hours
  image: mysql:8.0
  pvc: mysql-backups

primary:
  extraFlags: "--default-authentication-plugin=mysql_native_password"
  configuration: |
    [mysqld]
    skip-name-resolve
    default_authentication_plugin=mysql_native_password
    # Allow root from outside localhost
    [client]
    host=%
  persistence:
    size: 8Gi