auth:
  existingSecret: mysql-prod-secret
  secretKeys:
    rootPassword: mysql-root-password
    username: mysql-username
    password: mysql-password
    database: mysql-database

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

backup:
  schedule: "0 */6 * * *"
  image: mysql:8.0
  pvc: mysql-backups

primary:
  persistence:
    size: 8Gi