mysql:
  secretName: mysql-prod-secret
  database: proddb
  username: produser
  persistence:
    size: 5Gi

image:
  repository: vyking-mysql
  tag: prod
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

backup:
  schedule: "0 */6 * * *"   # every 6 hours
  image: mysql:8.0
  pvc: mysql-backups
