env:
  - name: MYSQL_HOST
    valueFrom:
      secretKeyRef:
        name: mysql-credentials-{{ .Values.env }}
        key: host
  - name: MYSQL_PORT
    valueFrom:
      secretKeyRef:
        name: mysql-credentials-{{ .Values.env }}
        key: port
  - name: MYSQL_USER
    valueFrom:
      secretKeyRef:
        name: mysql-credentials-{{ .Values.env }}
        key: username
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysql-credentials-{{ .Values.env }}
        key: password
  - name: MYSQL_DATABASE
    valueFrom:
      secretKeyRef:
        name: mysql-credentials-{{ .Values.env }}
        key: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
          - name: backend
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports:
              - containerPort: {{ .Values.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-backend
  ports:
      - port: {{ .Values.service.port }}
        targetPort: {{ .Values.service.port }}
