{{- if and .Values.backend.enabled .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vyking.backend.fullname" . }}
  namespace: {{ .Values.backend.namespace | default .Release.Namespace }}
  {{- with .Values.backend.ingress.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.backend.ingress.className }}
  ingressClassName: {{ .Values.backend.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.backend.ingress.host }}
      http:
        paths:
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "vyking.backend.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
  {{- end }}