{{- if and .Values.backend.enabled .Values.backend.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "vyking.backend.fullname" . }}
  namespace: {{ .Values.backend.namespace | default .Release.Namespace }}
  labels:
{{ include "vyking.componentLabels" (dict "root" . "component" "backend" "values" .Values.backend) | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "vyking.backend.fullname" . }}
  minReplicas: {{ .Values.backend.hpa.minReplicas }}
  maxReplicas: {{ .Values.backend.hpa.maxReplicas }}
  metrics:
  {{- if .Values.backend.hpa.cpuUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.hpa.cpuUtilization }}
  {{- end }}
  {{- if .Values.backend.hpa.memoryUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.hpa.memoryUtilization }}
  {{- end }}
{{- end }}
