{{- if .Values.frontend.enabled }}
{{- $backendNamespace := .Values.backend.namespace | default .Release.Namespace }}
{{- $backendServiceName := include "vyking.backend.fullname" . }}
{{- $backendHost := default (printf "%s.%s.svc.cluster.local" $backendServiceName $backendNamespace) .Values.frontend.backendService.host }}
{{- $backendPort := default .Values.backend.service.port .Values.frontend.backendService.port }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vyking.frontend.fullname" . }}
  namespace: {{ .Values.frontend.namespace | default .Release.Namespace }}
  labels:
{{ include "vyking.componentLabels" (dict "root" . "component" "frontend" "values" .Values.frontend) | indent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
{{ include "vyking.componentSelectorLabels" (dict "root" . "component" "frontend" "values" .Values.frontend) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "vyking.componentSelectorLabels" (dict "root" . "component" "frontend" "values" .Values.frontend) | indent 8 }}
        environment: {{ include "vyking.environment" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          env:
            - name: BACKEND_URL
              value: "http://{{ $backendHost }}:{{ $backendPort }}"
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: {{ .Values.frontend.probes.liveness.port }}
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: {{ .Values.frontend.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "vyking.frontend.fullname" . }}-nginx-config
{{- end }}
