replicaCount: 2

image:
  tag: prod

service:
  port: 8081

mysql:
  host: mysql-prod
  secretName: mysql-credentials-prod

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  liveness:
    path: /health
    port: 8081
    initialDelaySeconds: 5
  readiness:
    path: /health
    port: 8081
    initialDelaySeconds: 3
hpa:
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70
  memoryUtilization: 70
