replicaCount: 1

image:
  repository: vyking-backend
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081
mysql:
  secretName: mysql-dev-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

probes:
  liveness:
    path: /health
    port: 8081
    initialDelaySeconds: 5
  readiness:
    path: /health
    port: 8081
    initialDelaySeconds: 3
