replicaCount: 2
environment: dev

image:
  repository: vyking-backend
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081
mysql:
  secretName: mysql-credentials-dev

ingress:
  enabled: true
  host: frontend-dev.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 128Mi

probes:
  liveness:
    path: /health
    port: 8081
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 3

  readiness:
    path: /health
    port: 8081
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 5

labels:
  app.kubernetes.io/name: backend
  app.kubernetes.io/part-of: vyking-app
  environment: dev
