replicaCount: 1

image:
  repository: nginx
  tag: 1.27.2

service:
  port: 3001

ingress:
  enabled: true
  hosts:
    - host: frontend-dev.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 60
