replicaCount: 1

image:
  repository: vyking-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

backend:
  host: backend-backend.default.svc.cluster.local
  port: 8081

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

probes:
  liveness:
    path: /
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 15
  readiness:
    path: /
    port: 80
    initialDelaySeconds: 3
    periodSeconds: 10

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpuUtilization: 70
  memoryUtilization: 80
