replicaCount: 1

image:
  repository: vyking-frontend
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

backend:
  host: backend-dev
  port: 8081

ingress:
  enabled: true
  host: frontend-dev.local
  tls: []
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

probes:
  liveness:
    path: /
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    path: /
    port: 80
    initialDelaySeconds: 3
    periodSeconds: 8
    timeoutSeconds: 2
    failureThreshold: 3
