replicaCount: 2

image:
  repository: vyking-frontend
  tag: prod
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 8080

backend:
  host: backend-prod
  port: 8081

ingress:
  enabled: true
  host: frontend-dev.local
  tls: true


resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
