replicaCount: 3

image:
  repository: nginx
  tag: latest

service:
  port: 3000

ingress:
  enabled: true
  hosts:
    - host: frontend.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-tls
      hosts:
        - frontend.example.com

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  cpuUtilization: 70
  memoryUtilization: 80
