replicaCount: 1

image:
  repository: vyking-frontend
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

backend:
  host: backend-dev
  port: 8081

ingress:
  enabled: true
  host: frontend-dev.local
  tls: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
