{{- if and .Values.backend.enabled .Values.backend.ingress.enabled }}
{{- $root := . -}}
{{- $backend := $root.Values.backend -}}
{{- $name := include "vyking-app.backendFullname" $root -}}
{{- $namespace := default $root.Release.Namespace $backend.namespace -}}
{{- $pathPrefix := default "/api" $backend.ingress.path -}}
{{- $pathType := default "ImplementationSpecific" $backend.ingress.pathType -}}
{{- $cleanPath := trimSuffix "/" $pathPrefix -}}
{{- $normalizedPath := ternary "/" $cleanPath (eq $cleanPath "") -}}
{{- $renderedPath := ternary $normalizedPath (printf "%s(/|$)(.*)" $normalizedPath) (eq $pathType "Prefix") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  {{- with $backend.ingress.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ $backend.ingress.host }}
      http:
        paths:
          - path: {{ $renderedPath }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $backend.service.port }}
{{- end }}
