name: Terraform Deploy POC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: dev
      CLUSTER_NAME: vyking-dev
      NGINX_BASE: nginx:1.25-alpine
      PYTHON_BASE: python:3.11-slim-bullseye
      FE_IMAGE: vyking-frontend:dev
      BE_IMAGE: vyking-backend:dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install k3d & kubectl
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          k3d cluster create $CLUSTER_NAME --wait

      - name: Build and import images
        run: |
          docker build --build-arg BASE_IMAGE=$NGINX_BASE \
            -t $FE_IMAGE ./applications/frontend/app
          docker build --build-arg BASE_IMAGE=$PYTHON_BASE \
            -t $BE_IMAGE ./applications/backend/app
          k3d image import -c $CLUSTER_NAME $FE_IMAGE $BE_IMAGE

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Apply (dev)
        working-directory: terraform
        run: terraform apply -var-file=env/dev.tfvars -auto-approve

  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment: prod
    env:
      ENVIRONMENT: prod
      CLUSTER_NAME: vyking-prod
      NGINX_BASE: nginx:1.25-alpine
      PYTHON_BASE: python:3.11-slim-bullseye
      FE_IMAGE: vyking-frontend:prod
      BE_IMAGE: vyking-backend:prod

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install k3d & kubectl
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          k3d cluster create $CLUSTER_NAME --wait

      - name: Build and import images
        run: |
          docker build --build-arg BASE_IMAGE=$NGINX_BASE \
            -t $FE_IMAGE ./applications/frontend/app
          docker build --build-arg BASE_IMAGE=$PYTHON_BASE \
            -t $BE_IMAGE ./applications/backend/app
          k3d image import -c $CLUSTER_NAME $FE_IMAGE $BE_IMAGE

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Apply (prod)
        working-directory: terraform
        run: terraform apply -var-file=env/prod.tfvars -auto-approve
