name: Terraform Deploy POC

on:
  push:
    branches:
      - dev
      - prod
  workflow_dispatch:

jobs:
  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: dev
      CLUSTER_NAME: vyking-dev
      FE_IMAGE: vyking-frontend:dev
      BE_IMAGE: vyking-backend:dev

    steps:
      - uses: actions/checkout@v4

      - name: Install k3d & kubectl
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          k3d cluster create $CLUSTER_NAME --wait

      - name: Build and import im
